In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
import keras
from nltk.tokenize import TreebankWordTokenizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import keras.backend as K
from sklearn.externals import joblib
from keras.callbacks import EarlyStopping

Using TensorFlow backend.


In [2]:
feat = pd.read_csv('train_data.csv')
targets = pd.read_csv('train_reponse.csv')

In [3]:
df = feat.merge(targets)

In [4]:
df

review_id  \
0       CuAG9zG2VDdd4hPGMip2Xg   
1       oipDuz40GWRdhFI_ck0hmQ   
2       k7IdlhwtZ2evNJOkaKmPoQ   
3       xg1qeM_nYE0r0PYBZQedzg   
4       u3eX3oMz3hC2KfX3mdKBlA   
5       weJ-rLGzWKTIzhyDgomLSA   
6       6ZCeScwRyLiupX-7iOtX4w   
7       ePrwqwZ0w8RmeMcxym3EpA   
8       5eGl3SQ_9F6pf7MAZ4JykQ   
9       ZBxeVSGhxgS00_8Kyi9u5g   
10      oO4XuvWU86GSutZ8jsHvhg   
11      bRqN_gKkg2LUb1-fYuy3HA   
12      SxZB2EtQCoCD7OrvIjf1ag   
13      vFCW78zM4h1oMKx3dyR74A   
14      KyT9GhQqdaT1Odlk_PtEcA   
15      _hQywFfTkt0gWKRs5-qhDQ   
16      v95rpzwruYABipj8lUNGjA   
17      ElMwoPpO-CMIMhsxxzxMaw   
18      steyNxuhIj9KcSR6F15tFA   
19      JW5IS4QEFX_IqoslGO09Gg   
20      uyqsR38rRI2FHzOtS3pDFA   
21      HSgqiO0Sk_PcP6wjiDJe5A   
22      NTtQChYZvKFq8KcmtjukQw   
23      8w6WtmcQJ764Gh5eJQe7BQ   
24      BOvaxYX6nNKiCo76kbOAZQ   
25      lFMiLSx2-hRHYUuMWRCeDg   
26      d0-BMyIQlTRSKm20HMastg   
27      bNEJ16TsKiZF0Uan6Kf2pQ   
28      gVF2aZkBEGIsazavsv85EQ   
29      JwfVOuJtZo0o5bheTYTtNQ   
...                        ...   
499970  hcONsp7g0Vx8QweEmjWlVA   
499971  4swbQDfsYbMFvdBjikB0Tw   
499972  suBzPM9CK7ylVMbsBpxctg   
499973  58VHxSwBRGWZetFulStx0w   
499974  CLfogYERjL7mQpvYIvFuTg   
499975  JdiYcbkRtqvpUNiZARzKJQ   
499976  6inDiEE93CvraH5IKc9iFg   
499977  glWL6TJreX-pp60AZCpubw   
499978  sXhzUycmR39ewl4Zgpm6qw   
499979  nsWD_xA8rb7wUG766ZwPqg   
499980  JlxnQ7uFm4gmoKeovGFlKw   
499981  3v7EWCJfwDHK-cX5Jc5aCw   
499982  AXlEOyRuFvgeekUMpgYjcg   
499983  ssedthCVnH2TQH_KihiDMA   
499984  2GRtrWFqMLKISybGF09BXw   
499985  d83TLLObIsEHAiIoEUJGMA   
499986  VfHPqcC-vPJJH23oZfFhyw   
499987  GI0Y4_G7vLVMqDK19N9U7Q   
499988  UVW7aS6zVQxfORyOpPtgkg   
499989  3Zb0qonngSUgKZgVqk92Lg   
499990  vF7xtFrbANXLT90W1m_2Ig   
499991  XR4og1wnVTg7Eos40CMPMg   
499992  I6EJioeNTydzot32dRnOxA   
499993  _eegXWqtyc9k0RAEVnpIyg   
499994  -v2QxF9JWbHRG8D-TiYUcA   
499995  bFLRSIZl0K3modrtCGkmpA   
499996  kS_zIB1Ux1XyO69SDZI0tA   
499997  cwlrcezZ3N13GcULbzM1fA   
499998  mEBoraTE3vdrw_gW4HVdNQ   
499999  an2g7NYS0frN1KBT1Uc46g   

                                                     text  stars  
0       Deeeelicious!\n\nFirst, the upstairs is a pret...      4  
1       Just had a baby!\n\n...about a month ago. Had ...      5  
2       Since I was staying in the hotel we had a $25 ...      3  
3       I can't believe that I haven't reviewed this s...      5  
4       Mmmm so much choice and it's all completely aw...      5  
5       tried to go today at lunchtime:  but didn't re...      3  
6       To me, this is the BEST Sushi place in town an...      5  
7       i miss this place so much, it's insanity. \n\n...      5  
8       Love San Tan Village. It's conveniently locate...      4  
9       no hanky panky here.. the idea of these places...      5  
10      Throughout this review I've debated between 3 ...      3  
11      I've stayed in just about every hotel in Vegas...      5  
12      Food is amazing and so is the ambiance - elega...      5  
13      Never again...went in for a part and have them...      1  
14      I believe the cronuts are the best product the...      3  
15      They have a great selection but the prices are...      3  
16      If I could give this please more starts I easi...      5  
17      I am officially 5 lbs heavier than I was 2 hou...      4  
18      Ok Yelpers... this is the epitome of  value, a...      5  
19      I love this Barnes and Noble. It is always nea...      4  
20      Weera Thai is a wonderful Thai restaurant loca...      4  
21      We have stayed at this hotel once but we will ...      5  
22      It's fun to say, isn't it? Go ahead, it just r...      5  
23      So many hours clocked in here I can't begin to...      4  
24      The service was great! Horchata was awesome an...      5  
25      I like the set up. Staff is friendly. Kind of ...      4  
26      Ordered for delivery and never received my ord...      1  
27      Quick service. The employees

In [5]:
X = pd.DataFrame(df['text'])
y = df['stars']

In [6]:
vect = TfidfVectorizer(max_features=10000)

In [8]:
X = vect.fit_transform(X['text'])

In [23]:
joblib.dump(vect, 'vector.pkl')

['vector.pkl']

In [9]:
y = pd.get_dummies(y)
y.columns = ['stars_{}'.format(x) for x in y.columns]

In [10]:
y.head()

stars_1  stars_2  stars_3  stars_4  stars_5
0        0        0        0        1        0
1        0        0        0        0        1
2        0        0        1        0        0
3        0        0        0        0        1
4        0        0        0        0        1

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [12]:
X_train.shape

(375000, 10000)

In [13]:
K.clear_session()
model = Sequential()
opt = Adam()
es = EarlyStopping(patience=2)

In [15]:
model.add(Dense(units=64, activation='tanh', input_dim=len(vect.get_feature_names())))
model.add(Dense(4, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(5, activation='softmax'))

model.compile(opt, loss='categorical_crossentropy')

In [14]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                640064    
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 260       
_________________________________________________________________
dense_3 (Dense)              (None, 16)                80        
_________________________________________________________________
dense_4 (Dense)              (None, 5)                 85        
Total params: 640,489
Trainable params: 640,489
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.fit(X_train, y_train, batch_size=500, epochs=10, validation_split=0.1, callbacks=[es])

Train on 337500 samples, validate on 37500 samples
Epoch 1/10
337500/337500 [==============================] - 84s 248us/step - loss: 0.9758 - val_loss: 0.8621
Epoch 2/10
337500/337500 [==============================] - 54s 160us/step - loss: 0.8390 - val_loss: 0.8614
Epoch 3/10
337500/337500 [==============================] - 55s 163us/step - loss: 0.8245 - val_loss: 0.8599
Epoch 4/10
337500/337500 [==============================] - 56s 165us/step - loss: 0.8165 - val_loss: 0.8640
Epoch 5/10
337500/337500 [==============================] - 55s 164us/step - loss: 0.8107 - val_loss: 0.8644


In [15]:
model.evaluate(X_test, y_test)

125000/125000 [==============================] - 19s 155us/step


0.8167321469116211

In [16]:
predictions = model.predict(X_test)

In [17]:
from sklearnearn import metrics

In [20]:
target = df['stars']

In [44]:
pred = predictions.argmax(axis=1)+1
target = y_test.values.argmax(axis=1)+1

In [46]:
print(metrics.classification_report(target, pred))

              precision    recall  f1-score   support

           1       0.71      0.79      0.75     12553
           2       0.51      0.45      0.48     11263
           3       0.53      0.44      0.48     17722
           4       0.57      0.60      0.58     37163
           5       0.74      0.77      0.76     46299

   micro avg       0.64      0.64      0.64    125000
   macro avg       0.61      0.61      0.61    125000
weighted avg       0.64      0.64      0.64    125000



In [47]:
print(metrics.confusion_matrix(target, pred))

[[ 9885  1758   358   284   268]
 [ 2578  5114  2443   856   272]
 [  667  2440  7797  5892   926]
 [  312   521  3455 22147 10728]
 [  393   145   622  9644 35495]]


In [48]:
print(metrics.accuracy_score(target, pred))

0.643504


In [20]:
joblib.dump(model, 'model.pkl')

['model.pkl']

In [21]:
predictions = pd.DataFrame(predictions)
predictions.columns = ['stars_1', 'stars_2', 'stars_3', 'stars_4', 'stars_5']

In [22]:
predictions.head()

stars_1   stars_2   stars_3   stars_4   stars_5
0  2.619189e-03  0.018879  0.170540  0.323833  0.484129
1  2.313532e-07  0.000012  0.000843  0.131217  0.867928
2  6.319660e-01  0.284619  0.059927  0.010904  0.012584
3  5.687640e-06  0.000058  0.001648  0.144409  0.853878
4  1.446419e-05  0.000559  0.023755  0.357861  0.617811